# Generated by Django 4.0.4 on 2022-09-17 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=512)),
                ('price', models.FloatField()),
                ('available', models.BooleanField(default=True)),
                ('category', models.CharField(max_length=128)),
            ],
        ),
    ]
